### ISSUE TITLE
Servicios API comprobantes

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/cuentas_contables_crud#8]
- [x] Asociar HU
- [x] Realizar anotaciones a la HU por el desarrollador
- [x] Realizar anotaciones a la HU por el lider 
- [x] Pruebas unitarias según los lineamientos
- [x] Servicios para registrar en WSO2

**Comment by davidmm07** [comment]
https://docs.google.com/spreadsheets/d/1AjwlomSd4LFDXR5FkoKx0M06awqKabSv/edit#gid=2083849879

**Comment by davidmm07** [comment]
Tarea a revisión @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
- [x] Anotaciones realizadas en las historias de usuario

- [x] API registrada en wso2

Tarea Realizada

**Comment by DianaPatriciaRamirez** [comment]
Faltan la pruebas unitarias según los lineamientos. Ingeniero Felipe @Soulfilip-UD  por favor indicar el avance de estas pruebas.

**Comment by Soulfilip-UD** [comment]
Pruebas realizadas  en los PR #24  y #26

**Comment by Soulfilip-UD** [comment]
Se debe pedir a @jjvargass la integración con sonarq del repositorio, esto confirmara que las pruebas se realizaron aunque el code review de estas ya quedo y las tareas de @davidmm07  se dan por finalizadas.

**Comment by DianaPatriciaRamirez** [comment]
Por favor confirma con el ingeniero @jjvargass y luego referencia en este issue, las pruebas unitarias solicitadas, antes de cerrar issue.

**Comment by jjvargass** [comment]
Se valida el cumplimiento de los lineamientos y en la gran mayoría no se están cumpliendo.
link del documento. 

https://docs.google.com/document/d/1I8jdX28iWo7RU-FZEdAU5LrBmYCTzkf8d308RCteR90/edit?usp=sharing

Se corren las pruebas unitarias y fallaron, se requiere una especificación técnica si es que no se están pasando algunos parámetros necesarios. 

```
go test ./... -v
# github.com/udistrital/cuentas_contables_crud/tests/comprobantestestcases
comprobantestestcases/comprobante_test.go:24:42: missing ',' before newline in composite literal
comprobantestestcases/comprobante_test.go:28:36: missing ',' before newline in composite literal
comprobantestestcases/comprobante_test.go:31:19: missing ',' before newline in composite literal
comprobantestestcases/comprobante_test.go:37:43: expected ';', found err
comprobantestestcases/comprobante_test.go:40:2: expected '{', found 'var'
comprobantestestcases/comprobante_test.go:41:134: expected ';', found err
comprobantestestcases/comprobante_test.go:44:2: expected '{', found 'var'
comprobantestestcases/comprobante_test.go:46:94: expected ';', found err
comprobantestestcases/comprobante_test.go:54:2: expected '{', found 'defer'
comprobantestestcases/comprobante_test.go:67:23: missing ',' before newline in composite literal
comprobantestestcases/comprobante_test.go:71:19: missing ',' before newline in composite literal
FAIL	github.com/udistrital/cuentas_contables_crud/tests/comprobantestestcases [setup failed]
=== RUN   TestGet
2020/01/18 22:03:43.167 [D] [default_test.go:27]  testing TestGet Code[%d]



Failures:

  * /home/casa/cuentas_contables_crud/tests/default_test.go 

```

**Comment by Soulfilip-UD** [comment]
Se corrigen las pruebas unitarias existentes y estas corren sin problemas en local, para que funcionen en test se requiere que mientras se corren, se levante una base de datos de prueba con docker y drone. Esto ya que son pruebas unitarias y necesitan validar sus funciones de inserción, edición, consulta e eliminación.

Tarea que continuara en el Issue #35 

Tarea finalizada
Proceeding to close Issue 👾
